using System.Collections.Specialized;
using System.Text;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Documents;
using Avalonia.Controls.Metadata;
using Avalonia.Controls.Primitives;
using Avalonia.Input.Platform;
using Avalonia.Interactivity;
using Avalonia.Media;
using Markdig.Syntax;
using TextMateSharp.Grammars;

namespace LiveMarkdown.Avalonia;

/// <summary>
/// Represents a code block in a Markdown document.
/// This control is used to display code snippets with optional syntax highlighting.
/// </summary>
[TemplatePart(CodeLinesPanelName, typeof(Panel), IsRequired = true)]
[TemplatePart(ScrollViewerName, typeof(ScrollViewer), IsRequired = false)]
[TemplatePart(LanguageTextBlockName, typeof(TextBlock), IsRequired = false)]
[TemplatePart(ToggleTextWrapButtonName, typeof(ToggleButton), IsRequired = false)]
[TemplatePart(CopyButtonName, typeof(Button), IsRequired = false)]
public class CodeBlock : TemplatedControl
{
    private const string ScrollViewerName = "PART_ScrollViewer";
    private const string CodeLinesPanelName = "PART_CodeLines";
    private const string LanguageTextBlockName = "PART_LanguageTextBlock";
    private const string ToggleTextWrapButtonName = "PART_ToggleTextWrapButton";
    private const string CopyButtonName = "PART_CopyButton";

    /// <summary>
    /// Defines the <see cref="AutoSyntaxHighlight"/> property.
    /// </summary>
    public static readonly StyledProperty<bool> AutoSyntaxHighlightProperty =
        AvaloniaProperty.Register<CodeBlock, bool>(nameof(AutoSyntaxHighlight), true);

    /// <summary>
    /// Gets or sets a value indicating whether to automatically apply syntax highlighting when the code or language changes.
    /// </summary>
    public bool AutoSyntaxHighlight
    {
        get => GetValue(AutoSyntaxHighlightProperty);
        set => SetValue(AutoSyntaxHighlightProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="Language"/> property.
    /// </summary>
    public static readonly StyledProperty<string?> LanguageProperty =
        AvaloniaProperty.Register<CodeBlock, string?>(nameof(Language));

    /// <summary>
    /// Gets or sets the programming language of the code block.
    /// </summary>
    public string? Language
    {
        get => GetValue(LanguageProperty);
        set => SetValue(LanguageProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="ColorTheme"/> property.
    /// </summary>
    public static readonly StyledProperty<ThemeName> ColorThemeProperty =
        AvaloniaProperty.Register<CodeBlock, ThemeName>(
            nameof(ColorTheme),
            ThemeName.DarkPlus,
            inherits: true);

    /// <summary>
    /// Gets or sets the theme used for syntax highlighting.
    /// The value is inherited from an ancestor, so <see cref="MarkdownRenderer.CodeBlockColorTheme"/>
    /// can configure all code blocks generated by a renderer.
    /// </summary>
    public ThemeName ColorTheme
    {
        get => GetValue(ColorThemeProperty);
        set => SetValue(ColorThemeProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="CustomColorTheme"/> property.
    /// </summary>
    public static readonly StyledProperty<string?> CustomColorThemeProperty =
        AvaloniaProperty.Register<CodeBlock, string?>(
            nameof(CustomColorTheme),
            inherits: true);

    /// <summary>
    /// Gets or sets the name of a theme registered with <see cref="SyntaxHighlighting.RegisterCustomTheme"/>.
    /// When not set, <see cref="ColorTheme"/> is used.
    /// The value is inherited from an ancestor, so <see cref="MarkdownRenderer.CodeBlockCustomColorTheme"/>
    /// can configure all code blocks generated by a renderer.
    /// </summary>
    public string? CustomColorTheme
    {
        get => GetValue(CustomColorThemeProperty);
        set => SetValue(CustomColorThemeProperty, value);
    }

    /// <summary>
    /// Backing field for the <see cref="Code"/> property.
    /// </summary>
    public static readonly DirectProperty<CodeBlock, string?> CodeProperty =
        AvaloniaProperty.RegisterDirect<CodeBlock, string?>(
            nameof(Code),
            o => o.Code,
            (o, v) => o.Code = v);

    /// <summary>
    /// Defines the <see cref="IsCodeWrapped"/> property.
    /// </summary>
    public static readonly StyledProperty<bool> IsCodeWrappedProperty =
        AvaloniaProperty.Register<CodeBlock, bool>(nameof(IsCodeWrapped), true);

    /// <summary>
    /// Gets or sets a value indicating whether the code content is wrapped.
    /// </summary>
    public bool IsCodeWrapped
    {
        get => GetValue(IsCodeWrappedProperty);
        set => SetValue(IsCodeWrappedProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="TextWrapping"/> property.
    /// </summary>
    public static readonly DirectProperty<CodeBlock, TextWrapping> TextWrappingProperty =
        AvaloniaProperty.RegisterDirect<CodeBlock, TextWrapping>(
            nameof(TextWrapping),
            o => o.TextWrapping);

    /// <summary>
    /// Gets the text wrapping mode currently used by the code block.
    /// </summary>
    public TextWrapping TextWrapping =>
        IsCodeWrapped ? TextWrapping.Wrap : TextWrapping.NoWrap;

    /// <summary>
    /// Defines the <see cref="HorizontalScrollBarVisibility"/> property.
    /// </summary>
    public static readonly DirectProperty<CodeBlock, ScrollBarVisibility> HorizontalScrollBarVisibilityProperty =
        AvaloniaProperty.RegisterDirect<CodeBlock, ScrollBarVisibility>(
            nameof(HorizontalScrollBarVisibility),
            o => o.HorizontalScrollBarVisibility);

    /// <summary>
    /// Gets the horizontal scroll bar visibility currently used by the code block.
    /// </summary>
    public ScrollBarVisibility HorizontalScrollBarVisibility =>
        IsCodeWrapped ? ScrollBarVisibility.Disabled : ScrollBarVisibility.Auto;

    /// <summary>
    /// Gets or sets the whole code content, and applies syntax highlighting to it.
    /// </summary>
    public string? Code
    {
        get
        {
            if (chunks.Count == 0) return null;
            if (chunks.Count == 1) return chunks[0].ActualText;

            var text = new StringBuilder();
            for (var i = 0; i < chunks.Count; i++)
            {
                if (i > 0) text.Append(Environment.NewLine);
                text.Append(chunks[i].ActualText);
            }

            return text.ToString();
        }

        set
        {
            using (SuspendSyntaxHighlighting())
            {
                if (value is null)
                {
                    TrimLines(0);
                }
                else
                {
                    var lines = value.Split(["\r\n", "\r", "\n"], StringSplitOptions.None);
                    for (var i = 0; i < lines.Length; i++) SetLine(i, lines[i]);
                    TrimLines(lines.Length);
                }
            }

            if (AutoSyntaxHighlight) HighlightSyntax();
        }
    }

    /// <summary>
    /// Gets the inline collection of the FIRST text block holding this code.
    /// </summary>
    /// <remarks>
    /// A long block is split across several text blocks so that appending a line re-measures only
    /// the last of them (see <see cref="LinesPerChunk"/>), so this is the whole content only while
    /// the code is short enough to be one. <see cref="Code"/> reads all of them;
    /// <see cref="CodeTextBlocks"/> is the full list.
    /// </remarks>
    public InlineCollection Inlines => EnsureChunk(0).Inlines!;

    /// <summary>
    /// How many lines one text block holds.
    /// </summary>
    /// <remarks>
    /// A text block lays out as a single unit, so appending one line to a block of N re-measures and
    /// re-shapes all N -- which makes a streaming code block quadratic in its own length. Splitting
    /// it means an append pays for the tail only. Measured by streaming 200 lines and watching what
    /// one appended line costs in layout: 2,112 KB at 64 lines to a block, 971 at 32, 512 at 16, 297
    /// at 8, 180 at 4. Linear in the chunk, so what stops it going lower is what a block costs on its
    /// own -- by 4 the per-append node work has overtaken the layout, and a 200-line block would be
    /// 50 controls for selection and search to walk. Eight is where those meet.
    /// </remarks>
    internal static int LinesPerChunk = 8;

    /// <summary>Gets the text blocks this code is laid out in, in order.</summary>
    public IReadOnlyList<MarkdownTextBlock> CodeTextBlocks => chunks;

    private readonly List<MarkdownTextBlock> chunks = [];
    private Panel? linesPanel;

    /// <summary>Gets the number of code lines currently held.</summary>
    internal int LineCount => lineTexts.Count;

    /// <summary>
    /// Each line's plain text, as it was set.
    /// </summary>
    /// <remarks>
    /// Highlighting turns a line into a Span of styled runs, and it needs that line's text to key its
    /// tokens and to carry the rule stack into the next line. Concatenating the runs back together to
    /// get it costs a string per line of the WHOLE block on every append, for text this control was
    /// handed in the first place -- so it is kept instead.
    /// </remarks>
    private readonly List<string> lineTexts = [];

    /// <summary>The plain text of every line, in order.</summary>
    internal IReadOnlyList<string> LineTexts => lineTexts;

    /// <summary>The inline collections of every text block, for one highlighting pass over all of them.</summary>
    private IReadOnlyList<InlineCollection> ChunkInlines()
    {
        var collections = new InlineCollection[chunks.Count];
        for (var i = 0; i < chunks.Count; i++) collections[i] = chunks[i].Inlines!;
        return collections;
    }

    /// <summary>Creates text blocks up to and including <paramref name="index"/>, and returns that one.</summary>
    private MarkdownTextBlock EnsureChunk(int index)
    {
        while (chunks.Count <= index)
        {
            var block = new MarkdownTextBlock
            {
                Inlines = new InlineCollection(),
                SourceSpan = SourceSpan,

                // Each block would otherwise round its own height up to a whole pixel, so every
                // extra one added a pixel and pushed the code below it down -- the same code laid
                // out as one block or several has to land in the same place.
                UseLayoutRounding = false,
            };

            // What the template used to bind on its single text block. Neither can be left to
            // inheritance: the base MarkdownTextBlock style SETS FontFamily, and a style setter beats
            // an inherited value, so a block that does not bind it renders code in the proportional
            // UI font. TextWrapping is not an inherited property at all.
            block.Bind(TemplatedControl.FontFamilyProperty, this.GetObservable(FontFamilyProperty));
            block.Bind(TextBlock.TextWrappingProperty, this.GetObservable(TextWrappingProperty));
            if (AutoSyntaxHighlight) block.Inlines!.CollectionChanged += HandleInlinesChanged;

            chunks.Add(block);
            linesPanel?.Children.Add(block);
        }

        return chunks[index];
    }

    /// <summary>Sets the text of one code line, creating the text block that holds it if needed.</summary>
    /// <remarks>Lines are expected in ascending order, which is how a block is built and grown.</remarks>
    internal void SetLine(int lineIndex, string text)
    {
        var inlines = EnsureChunk(lineIndex / LinesPerChunk).Inlines!;
        var indexInChunk = lineIndex % LinesPerChunk;
        var offset = indexInChunk * 2;

        // A chunk alternates Run, LineBreak, Run ... so a line sits at an even index. Fill any gap,
        // which only arises if a caller skips a line.
        while (inlines.Count < offset)
        {
            inlines.Add(inlines.Count % 2 == 0 ? new Run(string.Empty) : new LineBreak());
        }

        if (inlines.Count == offset)
        {
            if (indexInChunk > 0 && inlines[offset - 1] is not LineBreak) inlines[offset - 1] = new LineBreak();
            inlines.Add(new Run(text));
        }
        else if (inlines[offset] is Run existing)
        {
            if (!string.Equals(existing.Text, text, StringComparison.Ordinal))
            {
                existing.Text = text;
                existing.Classes.Remove(SyntaxHighlighting.FormattedClassName);
            }
        }
        else
        {
            // A formatted line is a Span of styled runs; rewriting it starts again from plain text.
            inlines[offset] = new Run(text);
        }

        while (lineTexts.Count <= lineIndex) lineTexts.Add(string.Empty);
        lineTexts[lineIndex] = text;
    }

    /// <summary>Drops every line at or past <paramref name="count"/>.</summary>
    internal void TrimLines(int count)
    {
        var neededChunks = count == 0 ? 0 : (count - 1) / LinesPerChunk + 1;
        while (chunks.Count > neededChunks)
        {
            var block = chunks[^1];
            if (block.Inlines is { } blockInlines) blockInlines.CollectionChanged -= HandleInlinesChanged;
            linesPanel?.Children.Remove(block);
            chunks.RemoveAt(chunks.Count - 1);
        }

        if (chunks.Count > 0)
        {
            var inlines = chunks[^1].Inlines!;
            var linesInLast = count - ((chunks.Count - 1) * LinesPerChunk);
            var keep = Math.Max(0, (linesInLast * 2) - 1);
            while (inlines.Count > keep) inlines.RemoveAt(inlines.Count - 1);
        }

        if (lineTexts.Count > count) lineTexts.RemoveRange(count, lineTexts.Count - count);
    }

    /// <summary>
    /// Defines the <see cref="CopyingToClipboard"/> event.
    /// Handle this event to perform custom actions when the code block is copying to clipboard and prevent the default behavior by setting <see cref="RoutedEventArgs.Handled"/> to true.
    /// </summary>
    public static readonly RoutedEvent<RoutedEventArgs> CopyingToClipboardEvent =
        RoutedEvent.Register<TextBox, RoutedEventArgs>(nameof(CopyingToClipboard), RoutingStrategies.Bubble);

    /// <summary>
    /// Raised when the code block is copying to clipboard.
    /// </summary>
    public event EventHandler<RoutedEventArgs>? CopyingToClipboard
    {
        add => AddHandler(CopyingToClipboardEvent, value);
        remove => RemoveHandler(CopyingToClipboardEvent, value);
    }

    /// <summary>
    /// Gets the first <see cref="MarkdownTextBlock"/> holding this code, or null before any line is
    /// set. A long block has more; see <see cref="CodeTextBlocks"/>.
    /// </summary>
    public MarkdownTextBlock? CodeTextBlock => chunks.Count > 0 ? chunks[0] : null;

    /// <summary>
    /// Gets or sets the Markdown source span represented by the code text layout.
    /// The value is retained until the template text block is available.
    /// </summary>
    internal SourceSpan SourceSpan
    {
        get;
        set
        {
            field = value;
            foreach (var chunk in chunks) chunk.SourceSpan = value;
        }
    }

    private ScrollViewer? _scrollViewer;
    private IDisposable? _copyButtonClickedSubscription;
    private bool isApplyingSyntaxHighlighting; // prevent re-entrance
    private int suspendedHighlightCount;

    /// <summary>
    /// How many times this block has walked itself to highlight. A rewrite of the inlines should
    /// cost ONE, however many pieces it arrives in; see <see cref="SuspendSyntaxHighlighting"/>.
    /// </summary>
    internal int SyntaxHighlightPassCount { get; private set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="CodeBlock"/> class.
    /// </summary>
    public CodeBlock()
    {
    }

    private void HandleInlinesChanged(object? sender, NotifyCollectionChangedEventArgs e)
    {
        if (suspendedHighlightCount > 0) return;

        HighlightSyntax();
    }

    /// <summary>
    /// Holds off automatic highlighting until the returned scope is disposed, for a caller about to
    /// rewrite <see cref="Inlines"/> a piece at a time.
    /// </summary>
    /// <remarks>
    /// Every mutation of the collection otherwise re-enters highlighting, and highlighting walks the
    /// whole block to find its lines -- so rewriting one line of a long block walked it several times
    /// over to reach the same answer the last walk would have.
    /// </remarks>
    internal SuspendedHighlightScope SuspendSyntaxHighlighting()
    {
        suspendedHighlightCount++;
        return new SuspendedHighlightScope(this);
    }

    /// <summary>The scope returned by <see cref="SuspendSyntaxHighlighting"/>.</summary>
    internal readonly struct SuspendedHighlightScope(CodeBlock owner) : IDisposable
    {
        public void Dispose()
        {
            if (owner.suspendedHighlightCount > 0) owner.suspendedHighlightCount--;
        }
    }

    /// <summary>
    /// Called when the control's template is applied.
    /// </summary>
    /// <param name="e">The event arguments for the applied template.</param>
    protected override void OnApplyTemplate(TemplateAppliedEventArgs e)
    {
        base.OnApplyTemplate(e);

        if (_copyButtonClickedSubscription is not null)
        {
            _copyButtonClickedSubscription.Dispose();
            _copyButtonClickedSubscription = null;
        }

        linesPanel = e.NameScope.Find<Panel>(CodeLinesPanelName);
        if (linesPanel is null)
        {
            throw new InvalidOperationException($"{CodeLinesPanelName} is not found in the template.");
        }

        // Any text block built before the template arrived joins it now, in order.
        linesPanel.Children.Clear();
        foreach (var chunk in chunks)
        {
            chunk.SourceSpan = SourceSpan;
            linesPanel.Children.Add(chunk);
        }

        _scrollViewer = e.NameScope.Find<ScrollViewer>(ScrollViewerName);

        if (e.NameScope.Find<Button>(CopyButtonName) is { } copyButton)
        {
            _copyButtonClickedSubscription = copyButton.AddDisposableHandler(
                Button.ClickEvent,
                HandleCopyButtonClick,
                RoutingStrategies.Bubble,
                true);
        }
    }

    /// <summary>
    /// Called when an Avalonia property on the control changes.
    /// </summary>
    /// <param name="change">Details about the property change.</param>
    protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
    {
        base.OnPropertyChanged(change);

        if (change.Property == LanguageProperty)
        {
            if (AutoSyntaxHighlight) HighlightSyntax();
        }
        else if (change.Property == ColorThemeProperty)
        {
            if (AutoSyntaxHighlight) Code = Code; // re-apply syntax highlighting
        }
        else if (change.Property == CustomColorThemeProperty)
        {
            if (AutoSyntaxHighlight) Code = Code; // re-apply syntax highlighting
        }
        else if (change.Property == AutoSyntaxHighlightProperty)
        {
            foreach (var chunk in chunks)
            {
                if (chunk.Inlines is not { } chunkInlines) continue;

                if (change.NewValue is true) chunkInlines.CollectionChanged += HandleInlinesChanged;
                else chunkInlines.CollectionChanged -= HandleInlinesChanged;
            }
        }
        else if (change.Property == IsCodeWrappedProperty)
        {
            var isCodeWrapped = change.NewValue is true;

            var (textWrappingOldValue, textWrappingNewValue) = isCodeWrapped ?
                (TextWrapping.NoWrap, TextWrapping.Wrap) :
                (TextWrapping.Wrap, TextWrapping.NoWrap);
            RaisePropertyChanged(TextWrappingProperty, textWrappingOldValue, textWrappingNewValue);

            var (scrollBarVisibilityOldValue, scrollBarVisibilityNewValue) = isCodeWrapped ?
                (ScrollBarVisibility.Auto, ScrollBarVisibility.Disabled) :
                (ScrollBarVisibility.Disabled, ScrollBarVisibility.Auto);
            RaisePropertyChanged(HorizontalScrollBarVisibilityProperty, scrollBarVisibilityOldValue, scrollBarVisibilityNewValue);

            if (_scrollViewer is not null && linesPanel is not null)
            {
                linesPanel.Width = _scrollViewer.Viewport.Width;
                linesPanel.UpdateLayout(); // fix bug that the text does not resize correctly
                linesPanel.Width = double.NaN;
            }
        }
    }

    /// <summary>
    /// Applies syntax highlighting to the code block based on the specified language.
    /// </summary>
    public void HighlightSyntax()
    {
        if (isApplyingSyntaxHighlighting) return;
        if (string.IsNullOrWhiteSpace(Language) || LineCount == 0) return;

        SyntaxHighlightPassCount++;
        isApplyingSyntaxHighlighting = true;
        try
        {
            SyntaxHighlighting.Create(Language.ToLower()).FormatInlines(ChunkInlines(), ColorTheme, CustomColorTheme, lineTexts);
        }
        finally
        {
            isApplyingSyntaxHighlighting = false;
        }
    }

    private async void HandleCopyButtonClick(object? sender, RoutedEventArgs e)
    {
        try
        {
            var copyEventArgs = new RoutedEventArgs(CopyingToClipboardEvent);
            RaiseEvent(copyEventArgs);
            if (copyEventArgs.Handled) return;

            var text = Code;
            if (string.IsNullOrEmpty(text)) return;

            if (TopLevel.GetTopLevel(this)?.Clipboard is not { } clipboard)
            {
                if (MarkdownRenderer.VerboseLogger?.IsValid is true)
                {
                    MarkdownRenderer.VerboseLogger.Value.Log(this, "Clipboard is not available.");
                }

                return;
            }

            await clipboard.SetTextAsync(text);
        }
        catch (Exception ex)
        {
            if (MarkdownRenderer.VerboseLogger?.IsValid is true)
            {
                MarkdownRenderer.VerboseLogger.Value.Log(this, "Failed to copy code to clipboard: {Message}", ex.Message);
            }
        }
    }
}
