using System.Collections.Specialized;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Documents;
using Avalonia.Controls.Metadata;
using Avalonia.Controls.Primitives;
using Avalonia.Input.Platform;
using Avalonia.Interactivity;
using Avalonia.Media;
using Markdig.Syntax;
using TextMateSharp.Grammars;

namespace LiveMarkdown.Avalonia;

/// <summary>
/// Represents a code block in a Markdown document.
/// This control is used to display code snippets with optional syntax highlighting.
/// </summary>
[TemplatePart(CodeTextBlockName, typeof(MarkdownTextBlock), IsRequired = true)]
[TemplatePart(ScrollViewerName, typeof(ScrollViewer), IsRequired = false)]
[TemplatePart(LanguageTextBlockName, typeof(TextBlock), IsRequired = false)]
[TemplatePart(ToggleTextWrapButtonName, typeof(ToggleButton), IsRequired = false)]
[TemplatePart(CopyButtonName, typeof(Button), IsRequired = false)]
public class CodeBlock : TemplatedControl
{
    private const string ScrollViewerName = "PART_ScrollViewer";
    private const string CodeTextBlockName = "PART_CodeTextBlock";
    private const string LanguageTextBlockName = "PART_LanguageTextBlock";
    private const string ToggleTextWrapButtonName = "PART_ToggleTextWrapButton";
    private const string CopyButtonName = "PART_CopyButton";

    /// <summary>
    /// Defines the <see cref="AutoSyntaxHighlight"/> property.
    /// </summary>
    public static readonly StyledProperty<bool> AutoSyntaxHighlightProperty =
        AvaloniaProperty.Register<CodeBlock, bool>(nameof(AutoSyntaxHighlight), true);

    /// <summary>
    /// Gets or sets a value indicating whether to automatically apply syntax highlighting when the code or language changes.
    /// </summary>
    public bool AutoSyntaxHighlight
    {
        get => GetValue(AutoSyntaxHighlightProperty);
        set => SetValue(AutoSyntaxHighlightProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="Language"/> property.
    /// </summary>
    public static readonly StyledProperty<string?> LanguageProperty =
        AvaloniaProperty.Register<CodeBlock, string?>(nameof(Language));

    /// <summary>
    /// Gets or sets the programming language of the code block.
    /// </summary>
    public string? Language
    {
        get => GetValue(LanguageProperty);
        set => SetValue(LanguageProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="ColorTheme"/> property.
    /// </summary>
    public static readonly StyledProperty<ThemeName> ColorThemeProperty =
        AvaloniaProperty.Register<CodeBlock, ThemeName>(
            nameof(ColorTheme),
            ThemeName.DarkPlus,
            inherits: true);

    /// <summary>
    /// Gets or sets the theme used for syntax highlighting.
    /// The value is inherited from an ancestor, so <see cref="MarkdownRenderer.CodeBlockColorTheme"/>
    /// can configure all code blocks generated by a renderer.
    /// </summary>
    public ThemeName ColorTheme
    {
        get => GetValue(ColorThemeProperty);
        set => SetValue(ColorThemeProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="CustomColorTheme"/> property.
    /// </summary>
    public static readonly StyledProperty<string?> CustomColorThemeProperty =
        AvaloniaProperty.Register<CodeBlock, string?>(
            nameof(CustomColorTheme),
            inherits: true);

    /// <summary>
    /// Gets or sets the name of a theme registered with <see cref="SyntaxHighlighting.RegisterCustomTheme"/>.
    /// When not set, <see cref="ColorTheme"/> is used.
    /// The value is inherited from an ancestor, so <see cref="MarkdownRenderer.CodeBlockCustomColorTheme"/>
    /// can configure all code blocks generated by a renderer.
    /// </summary>
    public string? CustomColorTheme
    {
        get => GetValue(CustomColorThemeProperty);
        set => SetValue(CustomColorThemeProperty, value);
    }

    /// <summary>
    /// Backing field for the <see cref="Code"/> property.
    /// </summary>
    public static readonly DirectProperty<CodeBlock, string?> CodeProperty =
        AvaloniaProperty.RegisterDirect<CodeBlock, string?>(
            nameof(Code),
            o => o.Code,
            (o, v) => o.Code = v);

    /// <summary>
    /// Defines the <see cref="IsCodeWrapped"/> property.
    /// </summary>
    public static readonly StyledProperty<bool> IsCodeWrappedProperty =
        AvaloniaProperty.Register<CodeBlock, bool>(nameof(IsCodeWrapped), true);

    /// <summary>
    /// Gets or sets a value indicating whether the code content is wrapped.
    /// </summary>
    public bool IsCodeWrapped
    {
        get => GetValue(IsCodeWrappedProperty);
        set => SetValue(IsCodeWrappedProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="TextWrapping"/> property.
    /// </summary>
    public static readonly DirectProperty<CodeBlock, TextWrapping> TextWrappingProperty =
        AvaloniaProperty.RegisterDirect<CodeBlock, TextWrapping>(
            nameof(TextWrapping),
            o => o.TextWrapping);

    /// <summary>
    /// Gets the text wrapping mode currently used by the code block.
    /// </summary>
    public TextWrapping TextWrapping =>
        IsCodeWrapped ? TextWrapping.Wrap : TextWrapping.NoWrap;

    /// <summary>
    /// Defines the <see cref="HorizontalScrollBarVisibility"/> property.
    /// </summary>
    public static readonly DirectProperty<CodeBlock, ScrollBarVisibility> HorizontalScrollBarVisibilityProperty =
        AvaloniaProperty.RegisterDirect<CodeBlock, ScrollBarVisibility>(
            nameof(HorizontalScrollBarVisibility),
            o => o.HorizontalScrollBarVisibility);

    /// <summary>
    /// Gets the horizontal scroll bar visibility currently used by the code block.
    /// </summary>
    public ScrollBarVisibility HorizontalScrollBarVisibility =>
        IsCodeWrapped ? ScrollBarVisibility.Disabled : ScrollBarVisibility.Auto;

    /// <summary>
    /// An alternative property of <see cref="Inlines"/> to set the code content and apply syntax highlighting automatically.
    /// </summary>
    public string? Code
    {
        get => Inlines.Text;
        set
        {
            Inlines.Clear();
            if (value is null) return;

            // pause applying syntax highlighting while adding lines
            isApplyingSyntaxHighlighting = true;
            var lines = value.Split(["\r\n", "\r", "\n"], StringSplitOptions.None);
            for (var i = 0; i < lines.Length; i++)
            {
                Inlines.Add(lines[i]);
                if (i < lines.Length - 1) Inlines.Add(new LineBreak());
            }
            isApplyingSyntaxHighlighting = false;

            if (AutoSyntaxHighlight) HighlightSyntax();
        }
    }

    /// <summary>
    /// Gets the inline collection containing the code content.
    /// </summary>
    public InlineCollection Inlines { get; } = new();

    /// <summary>
    /// Defines the <see cref="CopyingToClipboard"/> event.
    /// Handle this event to perform custom actions when the code block is copying to clipboard and prevent the default behavior by setting <see cref="RoutedEventArgs.Handled"/> to true.
    /// </summary>
    public static readonly RoutedEvent<RoutedEventArgs> CopyingToClipboardEvent =
        RoutedEvent.Register<TextBox, RoutedEventArgs>(nameof(CopyingToClipboard), RoutingStrategies.Bubble);

    /// <summary>
    /// Raised when the code block is copying to clipboard.
    /// </summary>
    public event EventHandler<RoutedEventArgs>? CopyingToClipboard
    {
        add => AddHandler(CopyingToClipboardEvent, value);
        remove => RemoveHandler(CopyingToClipboardEvent, value);
    }

    /// <summary>
    /// Gets the <see cref="MarkdownTextBlock"/> control defined in the template, which is used to display the code content with syntax highlighting.
    /// </summary>
    public MarkdownTextBlock? CodeTextBlock { get; private set; }

    /// <summary>
    /// Gets or sets the Markdown source span represented by the code text layout.
    /// The value is retained until the template text block is available.
    /// </summary>
    internal SourceSpan SourceSpan
    {
        get;
        set
        {
            field = value;
            if (CodeTextBlock is not null) CodeTextBlock.SourceSpan = value;
        }
    }

    private ScrollViewer? _scrollViewer;
    private IDisposable? _copyButtonClickedSubscription;
    private bool isApplyingSyntaxHighlighting; // prevent re-entrance

    /// <summary>
    /// Initializes a new instance of the <see cref="CodeBlock"/> class.
    /// </summary>
    public CodeBlock()
    {
        Inlines.CollectionChanged += HandleInlinesChanged;
    }

    private void HandleInlinesChanged(object? sender, NotifyCollectionChangedEventArgs e)
    {
        HighlightSyntax();
    }

    /// <summary>
    /// Called when the control's template is applied.
    /// </summary>
    /// <param name="e">The event arguments for the applied template.</param>
    protected override void OnApplyTemplate(TemplateAppliedEventArgs e)
    {
        base.OnApplyTemplate(e);

        if (_copyButtonClickedSubscription is not null)
        {
            _copyButtonClickedSubscription.Dispose();
            _copyButtonClickedSubscription = null;
        }

        CodeTextBlock = e.NameScope.Find<MarkdownTextBlock>(CodeTextBlockName);
        if (CodeTextBlock is null)
        {
            throw new InvalidOperationException($"{CodeTextBlockName} is not found in the template.");
        }

        CodeTextBlock.Inlines = Inlines;
        CodeTextBlock.SourceSpan = SourceSpan;

        _scrollViewer = e.NameScope.Find<ScrollViewer>(ScrollViewerName);
        // TWEED FORK: a vertical wheel over a wide code block keeps scrolling the transcript.
        if (_scrollViewer is not null) WheelAxisRouting.Attach(_scrollViewer);

        if (e.NameScope.Find<Button>(CopyButtonName) is { } copyButton)
        {
            _copyButtonClickedSubscription = copyButton.AddDisposableHandler(
                Button.ClickEvent,
                HandleCopyButtonClick,
                RoutingStrategies.Bubble,
                true);
        }
    }

    /// <summary>
    /// Called when an Avalonia property on the control changes.
    /// </summary>
    /// <param name="change">Details about the property change.</param>
    protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
    {
        base.OnPropertyChanged(change);

        if (change.Property == LanguageProperty)
        {
            if (AutoSyntaxHighlight) HighlightSyntax();
        }
        else if (change.Property == ColorThemeProperty)
        {
            if (AutoSyntaxHighlight) Code = Code; // re-apply syntax highlighting
        }
        else if (change.Property == CustomColorThemeProperty)
        {
            if (AutoSyntaxHighlight) Code = Code; // re-apply syntax highlighting
        }
        else if (change.Property == AutoSyntaxHighlightProperty)
        {
            if (change.NewValue is true)
            {
                Inlines.CollectionChanged += HandleInlinesChanged;
            }
            else
            {
                Inlines.CollectionChanged -= HandleInlinesChanged;
            }
        }
        else if (change.Property == IsCodeWrappedProperty)
        {
            var isCodeWrapped = change.NewValue is true;

            var (textWrappingOldValue, textWrappingNewValue) = isCodeWrapped ?
                (TextWrapping.NoWrap, TextWrapping.Wrap) :
                (TextWrapping.Wrap, TextWrapping.NoWrap);
            RaisePropertyChanged(TextWrappingProperty, textWrappingOldValue, textWrappingNewValue);

            var (scrollBarVisibilityOldValue, scrollBarVisibilityNewValue) = isCodeWrapped ?
                (ScrollBarVisibility.Auto, ScrollBarVisibility.Disabled) :
                (ScrollBarVisibility.Disabled, ScrollBarVisibility.Auto);
            RaisePropertyChanged(HorizontalScrollBarVisibilityProperty, scrollBarVisibilityOldValue, scrollBarVisibilityNewValue);

            if (_scrollViewer is not null && CodeTextBlock is not null)
            {
                CodeTextBlock.Width = _scrollViewer.Viewport.Width;
                CodeTextBlock.UpdateLayout(); // fix bug that the text block does not resize correctly
                CodeTextBlock.Width = double.NaN;
            }
        }
    }

    /// <summary>
    /// Applies syntax highlighting to the code block based on the specified language.
    /// </summary>
    public void HighlightSyntax()
    {
        if (isApplyingSyntaxHighlighting) return;
        if (string.IsNullOrWhiteSpace(Language) || Inlines.Count == 0) return;

        isApplyingSyntaxHighlighting = true;
        try
        {
            SyntaxHighlighting.Create(Language.ToLower()).FormatInlines(Inlines, ColorTheme, CustomColorTheme);
        }
        finally
        {
            isApplyingSyntaxHighlighting = false;
        }
    }

    private async void HandleCopyButtonClick(object? sender, RoutedEventArgs e)
    {
        try
        {
            var copyEventArgs = new RoutedEventArgs(CopyingToClipboardEvent);
            RaiseEvent(copyEventArgs);
            if (copyEventArgs.Handled) return;

            var text = Inlines.Text;
            if (string.IsNullOrEmpty(text)) return;

            if (TopLevel.GetTopLevel(this)?.Clipboard is not { } clipboard)
            {
                if (MarkdownRenderer.VerboseLogger?.IsValid is true)
                {
                    MarkdownRenderer.VerboseLogger.Value.Log(this, "Clipboard is not available.");
                }

                return;
            }

            await clipboard.SetTextAsync(text);
        }
        catch (Exception ex)
        {
            if (MarkdownRenderer.VerboseLogger?.IsValid is true)
            {
                MarkdownRenderer.VerboseLogger.Value.Log(this, "Failed to copy code to clipboard: {Message}", ex.Message);
            }
        }
    }
}
