// @author https://github.com/DearVa
// @author https://github.com/AuroraZiling
// @author https://github.com/SlimeNull

using System.Windows.Input;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Metadata;
using Avalonia.Interactivity;
using Avalonia.Input;
using Avalonia.Logging;
using TextMateSharp.Grammars;

namespace LiveMarkdown.Avalonia;

/// <summary>
/// Renders a Markdown document into an Avalonia visual tree and coordinates selection,
/// link interaction, text search, and asynchronous document updates.
/// </summary>
[PseudoClasses(":link-pending", ":selecting")]
public partial class MarkdownRenderer : Control
{
    /// <summary>
    /// Defines the attached SelectionScopeName property.
    /// </summary>
    [Obsolete("Use MarkdownTextBlock.IsSelectionScope on the shared visual root instead.")]
    public static readonly AttachedProperty<string?> SelectionScopeNameProperty =
        AvaloniaProperty.RegisterAttached<MarkdownRenderer, Visual, string?>("SelectionScopeName");

    /// <summary>
    /// Sets the SelectionScopeName attached property on the given Visual.
    /// Visuals with the same SelectionScopeName belong to the same selection scope.
    /// <see cref="MarkdownRenderer"/>s in the same selection scope can be selected across each other.
    /// </summary>
    /// <param name="obj"></param>
    /// <param name="value"></param>
    [Obsolete("Use MarkdownTextBlock.IsSelectionScope on the shared visual root instead.")]
    public static void SetSelectionScopeName(Visual obj, string? value) => obj.SetValue(SelectionScopeNameProperty, value);

    /// <summary>
    /// Gets the SelectionScopeName attached property from the given Visual.
    /// </summary>
    /// <param name="obj"></param>
    /// <returns></returns>
    [Obsolete("Use MarkdownTextBlock.IsSelectionScope on the shared visual root instead.")]
    public static string? GetSelectionScopeName(Visual obj) => obj.GetValue(SelectionScopeNameProperty);

    /// <summary>
    /// Defines the <see cref="DocumentUpdate"/> property.
    /// </summary>
    public static readonly DirectProperty<MarkdownRenderer, MarkdownDocumentUpdate?> DocumentUpdateProperty =
        AvaloniaProperty.RegisterDirect<MarkdownRenderer, MarkdownDocumentUpdate?>(
            nameof(DocumentUpdate),
            o => o.DocumentUpdate,
            (o, v) => o.DocumentUpdate = v);

    /// <summary>
    /// Gets or applies a parsed Markdown document update.
    /// The update may be created on any thread, but must be assigned on the UI thread.
    /// </summary>
    public MarkdownDocumentUpdate? DocumentUpdate
    {
        get => documentUpdate;
        set => ApplyDocumentUpdate(value);
    }

    /// <summary>
    /// Defines the <see cref="ImageBasePath"/> property.
    /// </summary>
    public static readonly StyledProperty<string?> ImageBasePathProperty =
        AvaloniaProperty.Register<MarkdownRenderer, string?>(nameof(ImageBasePath));

    /// <summary>
    /// Base path for resolving relative image URLs.
    /// If not set, relative image URLs will not be resolved.
    /// Changing this property will not affect already rendered images.
    /// </summary>
    public string? ImageBasePath
    {
        get => GetValue(ImageBasePathProperty);
        set => SetValue(ImageBasePathProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="CodeBlockColorTheme"/> property.
    /// </summary>
    public static readonly StyledProperty<ThemeName> CodeBlockColorThemeProperty =
        CodeBlock.ColorThemeProperty.AddOwner<MarkdownRenderer>();

    /// <summary>
    /// Gets or sets the color theme used for syntax highlighting in code blocks.
    /// The value is inherited by code blocks generated by this renderer.
    /// </summary>
    public ThemeName CodeBlockColorTheme
    {
        get => GetValue(CodeBlockColorThemeProperty);
        set => SetValue(CodeBlockColorThemeProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="CodeBlockCustomColorTheme"/> property.
    /// </summary>
    public static readonly StyledProperty<string?> CodeBlockCustomColorThemeProperty =
        CodeBlock.CustomColorThemeProperty.AddOwner<MarkdownRenderer>();

    /// <summary>
    /// Gets or sets the registered custom theme name used for syntax highlighting in code blocks.
    /// When not set, <see cref="CodeBlockColorTheme"/> is used.
    /// The value is inherited by code blocks generated by this renderer.
    /// </summary>
    public string? CodeBlockCustomColorTheme
    {
        get => GetValue(CodeBlockCustomColorThemeProperty);
        set => SetValue(CodeBlockCustomColorThemeProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="LinkContextMenu"/> property.
    /// </summary>
    public static readonly StyledProperty<ContextMenu?> LinkContextMenuProperty =
        MarkdownTextBlock.LinkContextMenuProperty.AddOwner<MarkdownRenderer>();

    /// <summary>
    /// Context menu to show when right-clicking a link.
    /// The value is inherited by Markdown text blocks generated by this renderer.
    /// </summary>
    public ContextMenu? LinkContextMenu
    {
        get => GetValue(LinkContextMenuProperty);
        set => SetValue(LinkContextMenuProperty, value);
    }

    /// <summary>
    /// Raised when a Link is clicked.
    /// </summary>
    public event EventHandler<LinkClickedEventArgs>? LinkClick
    {
        add => AddHandler(MarkdownTextBlock.LinkClickEvent, value);
        remove => RemoveHandler(MarkdownTextBlock.LinkClickEvent, value);
    }

    /// <summary>
    /// Defines the <see cref="LinkCommand"/> property.
    /// </summary>
    public static readonly StyledProperty<ICommand?> LinkCommandProperty =
        AvaloniaProperty.Register<MarkdownRenderer, ICommand?>(nameof(LinkCommand));

    /// <summary>
    /// Command that is executed when a Link is clicked. Command parameter is <see cref="LinkClickedEventArgs"/>.
    /// </summary>
    public ICommand? LinkCommand
    {
        get => GetValue(LinkCommandProperty);
        set => SetValue(LinkCommandProperty, value);
    }

    private MarkdownDocumentUpdate? documentUpdate;

    private readonly DocumentNode documentNode;

    internal static readonly ParametrizedLogger? VerboseLogger;

    static MarkdownRenderer()
    {
        VerboseLogger = Logger.TryGet(LogEventLevel.Verbose, nameof(MarkdownRenderer));

        MarkdownTextBlock.LinkClickEvent.AddClassHandler<MarkdownRenderer>(HandleLinkClick);
        RequestBringIntoViewEvent.AddClassHandler<MarkdownRenderer>(HandleRequestBringIntoView);
    }

    private static void HandleLinkClick(MarkdownRenderer sender, LinkClickedEventArgs args)
    {
        if (args.Handled || sender.LinkCommand is not { } linkCommand || !linkCommand.CanExecute(args)) return;
        linkCommand.Execute(args);
    }

    private static void HandleRequestBringIntoView(MarkdownRenderer sender, RequestBringIntoViewEventArgs args)
    {
        // ignore requests from children
        args.Handled = true;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="MarkdownRenderer"/> class.
    /// </summary>
    public MarkdownRenderer()
    {
        documentNode = new DocumentNode(this);
        LogicalChildren.Add(documentNode.Control);
        VisualChildren.Add(documentNode.Control);

        // Keep one subscription for the renderer's lifetime. The pending version gates the work,
        // avoiding event-list churn while streaming updates arrive every layout cycle.
        LayoutUpdated += HandleLayoutUpdated;
        AddHandler(KeyDownEvent, HandleKeyDown);
        // A left press drops the selection, as every OS text surface does. TUNNEL phase with
        // handledEventsToo, because a press landing on something that HANDLES it — a button, an
        // expander chevron, an embedded control such as the Mermaid or Svg nodes — never reaches the
        // bubbling selection logic, and the highlight would just sit there.
        AddHandler(PointerPressedEvent, ClearSelectionOnPress, RoutingStrategies.Tunnel, handledEventsToo: true);
    }

    private void ClearSelectionOnPress(object? sender, PointerPressedEventArgs e)
    {
        if (!e.GetCurrentPoint(this).Properties.IsLeftButtonPressed) return;
        if (!HasSelection()) return;
        ClearSelection(GetVisibleMarkdownTextBlockDescendants(GetSelectionScopeRoot()));
        UpdateCanCopy();
    }

    private void ApplyDocumentUpdate(MarkdownDocumentUpdate? value)
    {
        Dispatcher.VerifyAccess();

        var previous = documentUpdate;
        if (!SetAndRaise(DocumentUpdateProperty, ref documentUpdate, value)) return;

        // Build detached renderers too, so attaching or realizing one never exposes an
        // intermediate empty tree before its first measure.
        if (value != null)
        {
            var change = value is MarkdownDocumentUpdate.Incremental incremental && previous is not null && incremental.Follows(previous)
                ? value.Change
                : new ObservableStringBuilderChangedEventArgs(
                    0,
                    Math.Max(previous?.Document.GetLength() ?? 0, value.Document.GetLength()),
                    value.Document.GetLength(),
                    value.Version);

            var time = DateTimeOffset.UtcNow;
            documentNode.Update(documentNode, value.Document, change, CancellationToken.None);

            if (VerboseLogger?.IsValid is true)
            {
                VerboseLogger.Value.Log(
                    this,
                    "Render markdown in {TotalMilliseconds} ms.",
                    (DateTimeOffset.UtcNow - time).TotalMilliseconds);
            }
        }
        else
        {
            documentNode.Clear();
        }

        RenderedTextProjection = null;
        if (value is not null)
        {
            // The search is NOT torn down here. Removing a named highlight that carries a foreground
            // rebuilds that block's text layout, so clearing every matched block and re-applying it
            // after the layout invalidated each of them twice per document update -- on a document
            // streaming in, that was most of what a keystroke cost. ApplyTextSearchCore already
            // diffs: it drops the highlight from blocks that no longer match and leaves a block whose
            // ranges are unchanged alone. It runs from LayoutUpdated, which is raised before the
            // frame is drawn, so nothing stale is ever painted.
            ScheduleRenderedTextStateRefresh(value.Version);
        }
        else
        {
            // Nothing will be laid out to re-apply against, so what is painted now has to go.
            ClearAppliedTextSearch();
            _pendingRenderedTextStateVersion = null;
        }

        InvalidateMeasure();
    }
}
