<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless"/>
    <PackageReference Include="Avalonia.Skia"/>
    <PackageReference Include="Avalonia.Fonts.Inter"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="NUnit"/>
    <PackageReference Include="NUnit3TestAdapter"/>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LiveMarkdown.Avalonia\LiveMarkdown.Avalonia.csproj"/>
    <ProjectReference Include="..\..\src\LiveMarkdown.Avalonia.Math\LiveMarkdown.Avalonia.Math.csproj"/>
    <ProjectReference Include="..\..\src\LiveMarkdown.Avalonia.Mermaid\LiveMarkdown.Avalonia.Mermaid.csproj"/>
  </ItemGroup>
</Project>
